openapi: 3.0.1
info:
  title: updcust
  description: Update a customer's details 
  version: 1.0.0
servers:
- url: /
paths:
  /customer:
    put:
      tags:
      - customer
      summary: Update customer record
      description: Uses the APICTRL CICS COMMAREA z/OS asset
      operationId: putCScustupd
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      requestBody:
        description: request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/putCScustupd_request'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putCScustupd_response_200'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'         
        '404':
          description: Customer Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'                      
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
      x-codegen-request-body-name: putCScustupd_request
  /customer/{custno}:
    get:
      tags:
      - customer
      summary: Read customer record
      description: Uses the INQCUST CICS COMMAREA z/OS asset
      operationId: getCScustinq
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: custno
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getCScustinq_response_200'     
        '404':
          description: Customer Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'                      
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
      x-codegen-request-body-name: putCScustupd_request
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: A message describing the error  
    putCScustupd_request:
      type: object
      properties:
        UpdCust:
          type: object
          properties:
            CustomerNumber:
              maxLength: 10
              type: string
            Name:
              maxLength: 60
              type: string
            Address:
              maxLength: 160
              type: string
    putCScustupd_response_200:
      type: object
      properties:
        UpdCust:
          type: object
          properties:
            CustomerNumber:
              maxLength: 10
              type: string
            Name:
              maxLength: 60
              type: string
            Address:
              maxLength: 160
              type: string
            UpdateSuccess:
              maxLength: 1
              type: string          
    getCScustinq_response_200:
      type: object
      properties:
        UpdCust:
          type: object
          properties:
            CustomerNumber:
              maxLength: 10
              type: string
            Name:
              maxLength: 60
              type: string
            Address:
              maxLength: 160
              type: string
            InquirySuccess:
              maxLength: 1
              type: string     
    getCScustenq_response_full_200:
      type: object
      properties:
        InqCustZ:
          type: object
          properties:
            InqCustEye:
              maxLength: 4
              type: string
            InqCustScode:
              maxLength: 6
              type: string
            InqCustCustno:
              maximum: 9999999999
              minimum: 0
              type: integer
            InqCustName:
              maxLength: 60
              type: string
            InqCustAddr:
              maxLength: 160
              type: string
            InqCustDob:
              type: object
              properties:
                InqCustDobDd:
                  maximum: 99
                  minimum: 0
                  type: integer
                InqCustDobMm:
                  maximum: 99
                  minimum: 0
                  type: integer
                InqCustDobYyyy:
                  maximum: 9999
                  minimum: 0
                  type: integer
            InqCustCreditScore:
              maximum: 999
              minimum: 0
              type: integer
            InqCustCsReviewDt:
              type: object
              properties:
                InqCustCsReviewDd:
                  maximum: 99
                  minimum: 0
                  type: integer
                InqCustCsReviewMm:
                  maximum: 99
                  minimum: 0
                  type: integer
                InqCustCsReviewYyyy:
                  maximum: 9999
                  minimum: 0
                  type: integer
            InqCustInqSuccess:
              maxLength: 1
              type: string
            InqCustInqFailCd:
              maxLength: 1
              type: string
            InqCustPcbPointer:
              maxLength: 4
              type: string   
x-original-swagger-version: "2.0"
